### PR TITLE
Dev integrate lmbench as regressions

### PR DESCRIPTION
**Pull request by mwookawa**
first add of lmbench suite into usr/tests

most tests aren't going to make sense in a barrelfish context or just want to touch unimplemented functionality. we want to strip this down to a min-max optimum of tests we can touch off as regressions.

### CODE REVIEW

**Comment by ghost** [comment]
Instead of just adding a copy, can you import lmbench on a branch so importing a newer version later doesn't require a lot of manual labor?

I know git has only rudimentary support for real branches but it should still be possible.

**Comment by mwookawa** [comment]
sorry, to be clear, the purpose of plopping lmbench in is that it is a simple set of C programs that we can use as regressions. we don't really care if there's a new release, as we're not actually benchmarking with it.

**Comment by ghost** [comment]
That's like saying "this code is temporary" :-)

**Comment by ghost** [comment]
but anyway, whatever... as long as I don't have to do the manual labor when the time comes I'm happy at that point to just say "I told you so" :-)

**Pull request merged**
