### PR TITLE
Docker config for MIPS/sys161

### PR DESCRIPTION
**Pull request by alexpatel**
It is a Dockerfile (with caching) that has installed on it BF toolchain and OS161 toolchain (from source). When you run the container it still builds/runs ARMv7 barrelfish, but CircleCI now runs the mips/sys161 container (on this branch).

* Using the source tarballs and instructions from http://os161.eecs.harvard.edu/
* The block where OS161-GDB is installed is commented out - we're sorting this out over e-mail

### CODE REVIEW

**Comment by alexpatel** [comment]
jk i removed all the armv7 toolchain dependencies so this circleci build will fail, but it should be okay to merge because we're not actually trying to run arm barrelfish on this image

**Comment by marikgoldstein** [comment]
I think it's okay to merge arm-breaking (the arch not the body part) things into this branch. Others' thoughts?

**Comment by alexpatel** [comment]
@marikgoldstein  I turned off the ARMv7 hake/build steps so that it passes CI - we can add back in commands when we get a platform together; see https://github.com/Harvard-PRINCESS/Guppy/pull/108/commits/5e2526bf604ab6107be1b6787b5d6e1c4d8c34f1

**Comment by ghost** [comment]
Looks ok to me, as far as that goes. I suspect the best solution for gdb is to update os161-gdb to a newer gdb; I'll look into that. You might also try adding -fgnu89-inline to CFLAGS, which you should be able to do with "env CFLAGS=-fgnu89-inline configure ..." before building.

**Comment by penlu** [comment]
lgtm

**Pull request merged**
