### PR TITLE
make arch-specific syscall functions more generic (x86_64 and arm)

### PR DESCRIPTION
**Pull request by jingmeihu**

### CODE REVIEW

**Comment by penlu** [comment]
* changes are mainly: code refactors moving syscall processing contents out to functions.
* caveat about this refactor: under pandaboard, the code associated with get_arch_id would return core ID---apic_id only exists under x86. so in order to build under pandaboard, this refactored code needs get_arch_id function commented out.
* so in kernel/syscall.c, comment out the get_arch_id function when building and running on pandaboard
ideally this would be done automatically via some kind of build config, but unsure how to do this, so this merge will attempt to retain full functionality for x86 by leaving it uncommitted---just make note of this when you're actually running on pandaboard.
* having done this, make PandaboardES succeeds, and fish behaves normally insofar as it ever has behaved normally

so: lgtm

**Comment by penlu** [comment]
it's been suggested that this actually be changed for architecture dependence, so holding off on the merge for now

**Comment by mwookawa** [comment]
crystal, can you sit down with eric and go over these changes tomorrow? once you two are convinced that it is good to go, can you highlight the most complex parts to review and then one of us can go over those and approve the PR. it generally looks good to me though as well, but it needs to build on all platforms out of the box.

**Comment by marikgoldstein** [comment]
Yes. And I think the pull request reviews will generally be good, but this
one is quite large because it's most of your work from the summer so far
(unavoidable because we just decided the git workflow)

**Comment by marikgoldstein** [comment]
Crystal and I reviewed the changes. In the future, we will run more regression tests. For now, it is good enough that PandaboardES ARMv7 and QEMU x86_64 both build and boot.

Through print statements, we observed that some of the syscalls are used during the boot. The following are not used during boot and should be checked later:
sys_handle_vnode_identify
sys_dispatcher_dump_capabilities
sys_dispatcher_dump_ptables
sys_monitor_has_descendants

**Pull request merged**
