### PR TITLE
Nightly build 2.0

### PR DESCRIPTION
**Pull request by alexpatel**
I've added in many of the desired features from the GOAT nightly build script, see [commit message](https://github.com/Harvard-PRINCESS/Guppy/commit/f996d5bf29e812f30de6da0d9c5d923e2e603c47) for details.

I didn't do auto-updating, if we change the script we should just replace the copy on nomnomnom - there are instructions on the readme.

Next, I will add hooks into the Python code in `Guppy/tools/harness` to actually run and test kernels in this script.

** Need to merge https://github.com/Harvard-PRINCESS/Guppy/pull/69 before merging this (and before reading the diff, otherwise you will just get everything and not the additions)

### CODE REVIEW

**Comment by alexpatel** [comment]
edit: pull again, I originally committed a crontab without the /usr/local/bin paths

**Comment by ghost** [comment]
In cleanbuilds() change "ls -td *" to "ls -td nightly-*" to match OLDEST. This will avoid doing the wrong thing if other files appear... and avoid doing quite the wrong thing if several others appear.

&> is a bashism. The portable way to write that is "> $TMP_FILE 2>&1".

Also if you're going to mail out the log rather than a diff of the log, better to send the end of it rather than the beginning. (Generally when a build fails the failure is relatively near the end of what's produced; that ends up being the beginning of a diff against a successful build log.)

(also, github questions: how do you actually do a review rather than just commenting? There doesn't seem to be a button for it on this page. And, is there a way to get a full diff of the whole pull request that I can attach comments to? Adding ".diff" to the pull request url gives a text diff, which is great for reading it without noise but not web-enabled...)

**Comment by alexpatel** [comment]
I've fixed ls -td/&>/"loca" and pushed upstream - I agree that things should be updateable by non-root (idk if Ming is issuing root accounts generally); I'll move everything into ~/bin tomorrow (will make into the next pull request, or if you hold off I will add to this one).

For Github, if you click on the "Files Changed" tab on a pull request ([example](https://github.com/Harvard-PRINCESS/Guppy/pull/70/files)), and then hover your mouse over any line of the diff and click on the blue + that pops up, you can add inline comments.

**Comment by alexpatel** [comment]
~~although there are certainly issues with the Github web UI, their code review workflow (inline comments in the patch) is really quite seemless and something to which I am not aware of a good "traditional" equivalent (e.g. email)~~

nvm, thinking about it clearly e-mail is the optimal code review tool - "inline comments in the patch" is built in lol...

**Comment by alexpatel** [comment]
Oh, and I will also add the diff feature - I was confused about that and was going to ask you today if we crossed paths, but I get it now...

**Comment by mwookawa** [comment]
I am handing out root accounts to nomnomnom and grizzly. Crystal uses her machine extensively as a remote desktop, so root may be more limited.

Alex, can you slack me on how to add the github intgrations you want from their continuous testing plugins list?

**Comment by alexpatel** [comment]
@mwookawa yep, will do (i believe it should just require some webhooks, no true GH integrations)

**Review by ghost — APPROVED** [review]
Seems ok; if there's anything more I'm not likely to spot it...

**Comment by alexpatel** [comment]
Great, thank you for reviewing, @dh6713!

I intend to also point BuildBot@nomnomnom to this script for continuous integration, so I may refactor a bit of the e-mail stuff so that we can have both running (in another branch)

**Pull request merged**
